#!/usr/bin/env python3
"""
Upload factor files to Lean Cloud ObjectStore.

This script uploads all factor JSON files generated by the rolling training
to the Lean Cloud ObjectStore, making them available for dynamic loading
by the live trading strategy.

Usage:
    # Upload all factors
    python scripts/upload_factors_to_objectstore.py

    # Upload specific month
    python scripts/upload_factors_to_objectstore.py --month 2024_01

    # Dry run (show what would be uploaded)
    python scripts/upload_factors_to_objectstore.py --dry-run

Prerequisites:
    - Lean CLI must be installed and configured
    - Must be logged in: `lean login`
    - Must have a cloud project set up
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path


def run_lean_command(args: list, dry_run: bool = False) -> bool:
    """
    Run a lean CLI command.

    Args:
        args: Command arguments
        dry_run: If True, only print the command without executing

    Returns:
        True if successful, False otherwise
    """
    cmd = ['lean'] + args

    if dry_run:
        print(f"  [DRY RUN] Would run: {' '.join(cmd)}")
        return True

    try:
        result = subprocess.run(
            cmd,
            check=True,
            capture_output=True,
            text=True
        )
        return True
    except subprocess.CalledProcessError as e:
        print(f"  ❌ Error: {e.stderr}")
        return False
    except FileNotFoundError:
        print("  ❌ Error: 'lean' command not found. Please install Lean CLI:")
        print("     pip install lean")
        return False


def upload_factor_file(factor_file: Path, dry_run: bool = False) -> bool:
    """
    Upload a single factor file to ObjectStore.

    Args:
        factor_file: Path to the factor JSON file
        dry_run: If True, only print what would be uploaded

    Returns:
        True if successful, False otherwise
    """
    # ObjectStore key: factors/YYYY_MM.json
    object_key = f"factors/{factor_file.name}"

    print(f"\nUploading {factor_file.name}...")
    print(f"  Source: {factor_file}")
    print(f"  Destination: ObjectStore key '{object_key}'")

    # Load and display factor info
    try:
        with open(factor_file, 'r') as f:
            factor_data = json.load(f)

        print(f"  Factors: {factor_data['n_factors']}")
        print(f"  Deploy month: {factor_data['deploy_month']}")
        print(f"  Train IC: {factor_data['train_ic']:.4f}")

    except Exception as e:
        print(f"  ⚠️  Warning: Could not read factor file: {e}")

    # Upload to ObjectStore
    success = run_lean_command([
        'cloud', 'object-store', 'set',
        object_key,
        '--file', str(factor_file)
    ], dry_run=dry_run)

    if success and not dry_run:
        print(f"  ✅ Uploaded successfully")
    elif success and dry_run:
        print(f"  ✅ Would upload successfully")

    return success


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Upload factor files to Lean Cloud ObjectStore",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )

    parser.add_argument(
        '--factors-dir',
        type=Path,
        default=Path('./lean_project/storage/factors'),
        help='Directory containing factor JSON files (default: ./lean_project/storage/factors)'
    )

    parser.add_argument(
        '--month',
        type=str,
        default=None,
        help='Upload only specific month (e.g., 2024_01)'
    )

    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Show what would be uploaded without actually uploading'
    )

    args = parser.parse_args()

    print(f"\n{'='*80}")
    print("Upload Factors to Lean Cloud ObjectStore")
    print(f"{'='*80}")
    print(f"Factors directory: {args.factors_dir}")
    if args.dry_run:
        print("Mode: DRY RUN (no actual uploads)")
    print(f"{'='*80}\n")

    # Check if factors directory exists
    if not args.factors_dir.exists():
        print(f"❌ Error: Factors directory not found: {args.factors_dir}")
        print("\nPlease run rolling training with --export-objectstore first:")
        print("  python scripts/run_rolling_train.py --export-objectstore")
        return 1

    # Get list of factor files
    if args.month:
        factor_files = [args.factors_dir / f"{args.month}.json"]
        if not factor_files[0].exists():
            print(f"❌ Error: Factor file not found: {factor_files[0]}")
            return 1
    else:
        factor_files = sorted(args.factors_dir.glob("*.json"))
        # Exclude manifest.json
        factor_files = [f for f in factor_files if f.name != "manifest.json"]

    if not factor_files:
        print(f"❌ Error: No factor files found in {args.factors_dir}")
        return 1

    print(f"Found {len(factor_files)} factor file(s) to upload\n")

    # Upload each file
    success_count = 0
    fail_count = 0

    for factor_file in factor_files:
        if upload_factor_file(factor_file, dry_run=args.dry_run):
            success_count += 1
        else:
            fail_count += 1

    # Summary
    print(f"\n{'='*80}")
    print("Upload Summary")
    print(f"{'='*80}")
    print(f"Total files: {len(factor_files)}")
    print(f"Successful: {success_count}")
    print(f"Failed: {fail_count}")

    if args.dry_run:
        print("\nThis was a dry run. Use without --dry-run to actually upload.")
    elif success_count > 0:
        print(f"\n✅ Upload complete!")
        print("\nFactors are now available in ObjectStore under 'factors/' prefix")
        print("Your live trading strategy will automatically load them when the month changes.")
    else:
        print(f"\n❌ All uploads failed")
        return 1

    print(f"{'='*80}\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
